### ISSUE TITLE
Cosmetic: add option for space in self-closing tag

### ISSUE THREAD

**Issue by FloEdelmann** [oozcitak/xmlbuilder-js#157] opened 2017-05-16 21:30 UTC
In self-closing tags, there is no space before the slash (`<tag/>` instead of `<tag />`). I know this is purely cosmetic, but I prefer having a space there.

It would be nice to be able to control this behaviour with an option.

Bonus: The option could also add a space in the XML header: `<?xml version="1.0" encoding="UTF-8" ?>` instead of `<?xml version="1.0" encoding="UTF-8"?>`

**Comment by soumak77** [comment] 2017-08-15 03:39
This would be very useful when using this library to modify a cordova config.xml.  Cordova uses a space before the closing tag.  As a result, any minor changes with this library looks like a massive rewrite to the file since every line is included in the diff.

**Closed** 2017-08-15 13:32 UTC

**Comment by soumak77** [comment] 2017-08-15 20:25
@oozcitak this feature is broken.  Instead of adding a space, it adds the word `true`.

```xml
    <content src="index.html"true/>
    <access origin="*"true/>
    <allow-navigation href="http://ionic.local/*"true/>
    <allow-navigation href="http://192.168.1.226:8100"true/>
    <allow-intent href="http://*/*"true/>
    <allow-intent href="https://*/*"true/>
    <allow-intent href="tel:*"true/>
    <allow-intent href="sms:*"true/>
    <allow-intent href="mailto:*"true/>
    <allow-intent href="geo:*"true/>
```

**Comment by soumak77** [comment] 2017-08-16 03:07
@oozcitak I expected the `spacebeforeslash` option to accept `true` or `false`, however, this yields the results above.  If I set the option to `' '` then it works as expected.

**Comment by oozcitak** [comment] 2017-08-16 10:20
This is by design. It requires the string to be inserted before the closing slash. See the wiki: https://github.com/oozcitak/xmlbuilder-js/wiki#converting-to-string

**Comment by oozcitak** [comment] 2017-08-16 11:45
I am adding a check for boolean true as well: 63d5143
